### ISSUE TITLE
cannot open the SAP Corporate Contributor License Agreement.pdf 

### ISSUE THREAD

**Issue by luisapace** [SAP/java-memory-assistant#10]
Hi, opening the SAP Corporate Contributor License Agreement.pdf goes in error with the message:
_**_"Sorry, this file is invalid so it cannot be displayed"._**_ 
Could you please insert the right file or insert here a link to a readable file? Thanks.

**Comment by thsandfuchs** [comment]
Thanks for notifying us - we will take a look what changed here and broke.
